import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "../globals.css";
import Providers from "@/components/Themes/Provider";
import Defaultlayout from "@/components/common/Default-layout";
const inter = Outfit({ subsets: ["latin"] });
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import { Locale } from "@/i18n.config";
const amiri = IBM_Plex_Sans_Arabic({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Desinoir - Designing Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body
        className={`${params.lang == "en" ? inter.className : amiri.className}`}
      >
        <Providers>
          <Defaultlayout>{children}</Defaultlayout>
        </Providers>
      </body>
    </html>
  );
}
