import React, { useEffect, useState } from "react";
// import '../../globals.css';
import { getDictionary } from "@/dictionary";
import { Locale } from "@/i18n.config";
import ContactUsMain from "./ContactUsMain";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Contact - Desinoir - Designing Agency",
  description: "Generated by create next app",
};
async function Page({ params }: { params: { lang: Locale } }) {
  const direction = params.lang == "en" ? "ltr" : "rtl";
  const { parent }: any = await getDictionary(params.lang);

  return (
    <>
      <ContactUsMain parent={parent} direction={direction} lang={params.lang} />
    </>
  );
}

export default Page;
