import Branding from "@/components/About/Branding";
import ChooseUs from "@/components/About/ChooseUs";
import CompletedProjects from "@/components/CompletedProjects";
import Footer from "@/components/common/Footer";
import Pagesheader from "@/components/common/Pagesheader";
import Testimonial from "@/components/common/Testimonials";
import Creativity from "@/components/home/Creativity";
import Experties from "@/components/home/Experties";
import Team from "@/components/home/Team";
import { getDictionary } from "@/dictionary";
import { Locale } from "@/i18n.config";
import { Metadata } from "next";
import React from "react";
const points = {
  pt1: `UI/UX Designing`,
  pt2: `Branding`,
  pt3: `Graphic Designing`,
  pt4: `Motion Graphic Designing`,
};
const pointsArabic = {
  pt1: "تصميم واجهة المستخدم / تجربة المستخدم",
  pt2: "تسويق العلامة التجارية",
  pt3: "تصميم الجرافيك",
  pt4: "تصميم الجرافيك المتحرك",
};
const Teams = [
  {
    id: 1,
    img: "/assets/about/shehzad.png",
    img2: "/assets/about/shehzad.color.png",
    name: "Shahzad Jameel",
    role: "Founder",
  },
  {
    id: 2,
    img: "/assets/about/umar.png",
    img2: "/assets/about/umar.color.png",
    name: "Muhammad Umer",
    role: "CEO",
  },
  {
    id: 3,
    img: "/assets/about/umar.J.png",
    img2: "/assets/about/umar.jcolor.png",
    name: "Umer Maqsood",
    role: "UI/UX Expert",
  },
];
export const metadata: Metadata = {
  title: "About - Designing Agency",
  description: "Generated by create next app",
};
async function About({ params }: { params: { lang: Locale } }) {
  const direction = params.lang == "en" ? "ltr" : "rtl";
  const { parent }: any = await getDictionary(params.lang);
  return (
    <div dir={direction}>
      <Pagesheader
        direction={direction}
        lang={params.lang}
        parent={parent}
        txt1={parent?.page?.AboutUs}
        txt2={parent?.page?.Us}
        img="/assets/about/OBJECTS.svg"
      />
      <div>
        <Creativity
          direction={direction}
          parent={parent}
          lang={params.lang}
          showtools={true}
          tools={params.lang == "en" ? points : pointsArabic}
          show={false}
          btn={true}
        />
      </div>
      <CompletedProjects />
      <Branding />
      <ChooseUs parent={parent} />
      <div className="">
        <Testimonial parent={parent} brandshow={false} />
      </div>
      <Team
        parent={parent}
        direction={direction}
        TeamMemnbers={Teams}
        btn={true}
      />
      <Experties aboutpb={false} parent={parent} direction={direction} />
      <Footer
        direction={direction}
        lang={params.lang}
        parent={parent}
        welnote={false}
      />
    </div>
  );
}

export default About;
