import React, { useEffect, useState } from "react";
// import '../../globals.css';
import { Locale } from "../../../i18n.config";
import { getDictionary } from "@/dictionary";
import Projects from "./Projects";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Our Projects - Desinoir - Designing Agency",
  description: "Generated by create next app",
};
async function Page({ params: { lang } }: { params: { lang: Locale } }) {
  const direction = lang == "en" ? "ltr" : "rtl";
  const { parent }: any = await getDictionary(lang);

  return (
    <>
      <Projects lang={lang} direction={direction} parent={parent} />
    </>
  );
}

export default Page;
