import TeamPage from "@/components/TeamPage";
import { getDictionary } from "@/dictionary";
import { Locale } from "@/i18n.config";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Our Creative Crew - Desinoir - Designing Agency",
  description: "Generated by create next app",
};
async function Page({ params: { lang } }: { params: { lang: Locale } }) {
  const direction = lang == "en" ? "ltr" : "rtl";
  const { parent }: any = await getDictionary(lang);
  return (
    <div>
      <TeamPage parent={parent} direction={direction} lang={lang} />
    </div>
  );
}

export default Page;
